name: PR Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*
      - dev/*


jobs:
  validate:
    name: Test and Validate Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m pytest -v


      - name: Docker Build Validation
        run: |
          docker build \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${{ github.sha }} \
            --build-arg VERSION=$(cat VERSION) \
            -t student-ml-api:ci-test .
